Search.appendIndex(
    [
                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine",
            "name": "CentralTendencyEngine",
            "summary": "CentralTendencyEngine\u0020\u002D\u0020robust\u0020central\u0020tendency\u0020estimators.",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003AtrimmedMean\u0028\u0029",
            "name": "trimmedMean",
            "summary": "Compute\u0020the\u0020trimmed\u0020mean\u0020by\u0020removing\u0020a\u0020percentage\u0020from\u0020each\u0020tail.",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_trimmedMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003AwinsorizedMean\u0028\u0029",
            "name": "winsorizedMean",
            "summary": "Compute\u0020the\u0020winsorized\u0020mean\u0020using\u0020quantile\u0020cut\u0020points.",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_winsorizedMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003AhuberMean\u0028\u0029",
            "name": "huberMean",
            "summary": "Compute\u0020the\u0020Huber\u0020M\u002Destimator\u0020for\u0020location.",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_huberMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003AvalidateTrimPercentage\u0028\u0029",
            "name": "validateTrimPercentage",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_validateTrimPercentage"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003AnormalizeData\u0028\u0029",
            "name": "normalizeData",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_normalizeData"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003Amean\u0028\u0029",
            "name": "mean",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_mean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003Amedian\u0028\u0029",
            "name": "median",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_median"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003Amad\u0028\u0029",
            "name": "mad",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#method_mad"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003ADEFAULT_TRIM_PERCENTAGE",
            "name": "DEFAULT_TRIM_PERCENTAGE",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#constant_DEFAULT_TRIM_PERCENTAGE"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003ADEFAULT_QUANTILE_TYPE",
            "name": "DEFAULT_QUANTILE_TYPE",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#constant_DEFAULT_QUANTILE_TYPE"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003ADEFAULT_HUBER_K",
            "name": "DEFAULT_HUBER_K",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#constant_DEFAULT_HUBER_K"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003ADEFAULT_HUBER_MAX_ITERATIONS",
            "name": "DEFAULT_HUBER_MAX_ITERATIONS",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#constant_DEFAULT_HUBER_MAX_ITERATIONS"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\CentralTendencyEngine\u003A\u003ADEFAULT_HUBER_TOLERANCE",
            "name": "DEFAULT_HUBER_TOLERANCE",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-CentralTendencyEngine.html#constant_DEFAULT_HUBER_TOLERANCE"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats",
            "name": "ClassicStats",
            "summary": "ClassicStats\u0020\u002D\u0020Classical\u0020descriptive\u0020statistics\u0020library.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetMean\u0028\u0029",
            "name": "getMean",
            "summary": "Calculate\u0020the\u0020simple\u0020arithmetic\u0020mean.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetMedian\u0028\u0029",
            "name": "getMedian",
            "summary": "Calculate\u0020the\u0020median\u0020\u0028sorting\u0020data\u0020first\u0029.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getMedian"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetDeviation\u0028\u0029",
            "name": "getDeviation",
            "summary": "Contract\u0020implementation\u003A\u0020returns\u0020the\u0020sample\u0020standard\u0020deviation.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getDeviation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetStandardDeviation\u0028\u0029",
            "name": "getStandardDeviation",
            "summary": "Calculate\u0020the\u0020sample\u0020standard\u0020deviation\u0020\u0028square\u0020root\u0020of\u0020sample\u0020variance\u0029.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getStandardDeviation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetCoefficientOfVariation\u0028\u0029",
            "name": "getCoefficientOfVariation",
            "summary": "Contract\u0020implementation\u003A\u0020returns\u0020the\u0020coefficient\u0020of\u0020variation\u0020\u0028CV\u0025\u0029.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getCoefficientOfVariation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetSampleVariance\u0028\u0029",
            "name": "getSampleVariance",
            "summary": "Calculate\u0020the\u0020sample\u0020variance\u0020\u0028Bessel\u0020correction\u003A\u0020divide\u0020by\u0020n\u002D1\u0029.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getSampleVariance"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetPopulationVariance\u0028\u0029",
            "name": "getPopulationVariance",
            "summary": "Calculate\u0020the\u0020population\u0020variance\u0020\u0028divide\u0020by\u0020n\u0029.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getPopulationVariance"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetOutliers\u0028\u0029",
            "name": "getOutliers",
            "summary": "Detect\u0020outliers\u0020using\u0020the\u0020traditional\u0020Z\u002DScore\u0020method\u0020\u0028\u007CZ\u007C\u0020\u003E\u00203\u0029.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getOutliers"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AgetSummary\u0028\u0029",
            "name": "getSummary",
            "summary": "Get\u0020a\u0020complete\u0020summary\u0020of\u0020classic\u0020metrics.",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_getSummary"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AcalculateMean\u0028\u0029",
            "name": "calculateMean",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_calculateMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AcalculateMedian\u0028\u0029",
            "name": "calculateMedian",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_calculateMedian"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\ClassicStats\u003A\u003AcalculateVariance\u0028\u0029",
            "name": "calculateVariance",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-ClassicStats.html#method_calculateVariance"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts\\StatsInterface",
            "name": "StatsInterface",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Contracts-StatsInterface.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts\\StatsInterface\u003A\u003AgetMean\u0028\u0029",
            "name": "getMean",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Contracts-StatsInterface.html#method_getMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts\\StatsInterface\u003A\u003AgetMedian\u0028\u0029",
            "name": "getMedian",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Contracts-StatsInterface.html#method_getMedian"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts\\StatsInterface\u003A\u003AgetDeviation\u0028\u0029",
            "name": "getDeviation",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Contracts-StatsInterface.html#method_getDeviation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts\\StatsInterface\u003A\u003AgetCoefficientOfVariation\u0028\u0029",
            "name": "getCoefficientOfVariation",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Contracts-StatsInterface.html#method_getCoefficientOfVariation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts\\StatsInterface\u003A\u003AgetOutliers\u0028\u0029",
            "name": "getOutliers",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Contracts-StatsInterface.html#method_getOutliers"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts\\StatsInterface\u003A\u003AgetSummary\u0028\u0029",
            "name": "getSummary",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Contracts-StatsInterface.html#method_getSummary"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Exceptions\\InvalidDataSetException",
            "name": "InvalidDataSetException",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Exceptions-InvalidDataSetException.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine",
            "name": "QuantileEngine",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003Acalculate\u0028\u0029",
            "name": "calculate",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_calculate"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AcalculateSorted\u0028\u0029",
            "name": "calculateSorted",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_calculateSorted"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AcalculateInternal\u0028\u0029",
            "name": "calculateInternal",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_calculateInternal"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AnormalizeData\u0028\u0029",
            "name": "normalizeData",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_normalizeData"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AcalculateDiscrete\u0028\u0029",
            "name": "calculateDiscrete",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_calculateDiscrete"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AcalculateType2\u0028\u0029",
            "name": "calculateType2",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_calculateType2"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AapplyType2Averaging\u0028\u0029",
            "name": "applyType2Averaging",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_applyType2Averaging"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AcalculateContinuous\u0028\u0029",
            "name": "calculateContinuous",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_calculateContinuous"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\QuantileEngine\u003A\u003AgetHyndmanFanParameters\u0028\u0029",
            "name": "getHyndmanFanParameters",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-QuantileEngine.html#method_getHyndmanFanParameters"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats",
            "name": "RobustStats",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetMean\u0028\u0029",
            "name": "getMean",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetMedian\u0028\u0029",
            "name": "getMedian",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getMedian"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetDeviation\u0028\u0029",
            "name": "getDeviation",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getDeviation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetCoefficientOfVariation\u0028\u0029",
            "name": "getCoefficientOfVariation",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getCoefficientOfVariation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetRobustDeviation\u0028\u0029",
            "name": "getRobustDeviation",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getRobustDeviation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetRobustCv\u0028\u0029",
            "name": "getRobustCv",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getRobustCv"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetRobustVariance\u0028\u0029",
            "name": "getRobustVariance",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getRobustVariance"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetIqr\u0028\u0029",
            "name": "getIqr",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getIqr"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetMad\u0028\u0029",
            "name": "getMad",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getMad"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetOutliers\u0028\u0029",
            "name": "getOutliers",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getOutliers"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetTrimmedMean\u0028\u0029",
            "name": "getTrimmedMean",
            "summary": "Trimmed\u0020mean\u0020by\u0020removing\u0020a\u0020percentage\u0020from\u0020each\u0020tail.",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getTrimmedMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetWinsorizedMean\u0028\u0029",
            "name": "getWinsorizedMean",
            "summary": "Winsorized\u0020mean\u0020using\u0020quantile\u0020cut\u0020points.",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getWinsorizedMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetHuberMean\u0028\u0029",
            "name": "getHuberMean",
            "summary": "Huber\u0020M\u002Destimator\u0020for\u0020robust\u0020location.",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getHuberMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetConfidenceIntervals\u0028\u0029",
            "name": "getConfidenceIntervals",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getConfidenceIntervals"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AgetSummary\u0028\u0029",
            "name": "getSummary",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_getSummary"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcalculateMean\u0028\u0029",
            "name": "calculateMean",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_calculateMean"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcalculateMedian\u0028\u0029",
            "name": "calculateMedian",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_calculateMedian"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcalculateRobustDeviation\u0028\u0029",
            "name": "calculateRobustDeviation",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_calculateRobustDeviation"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcalculateRobustCv\u0028\u0029",
            "name": "calculateRobustCv",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_calculateRobustCv"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcalculateIqr\u0028\u0029",
            "name": "calculateIqr",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_calculateIqr"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcalculateMad\u0028\u0029",
            "name": "calculateMad",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_calculateMad"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AdetectOutliers\u0028\u0029",
            "name": "detectOutliers",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_detectOutliers"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcalculateConfidenceIntervals\u0028\u0029",
            "name": "calculateConfidenceIntervals",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_calculateConfidenceIntervals"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003AcollectOutliers\u0028\u0029",
            "name": "collectOutliers",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#method_collectOutliers"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_1",
            "name": "TYPE_1",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_1"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_2",
            "name": "TYPE_2",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_2"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_3",
            "name": "TYPE_3",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_3"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_4",
            "name": "TYPE_4",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_4"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_5",
            "name": "TYPE_5",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_5"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_6",
            "name": "TYPE_6",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_6"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_7",
            "name": "TYPE_7",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_7"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_8",
            "name": "TYPE_8",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_8"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_9",
            "name": "TYPE_9",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_9"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\RobustStats\u003A\u003ATYPE_R_DEFAULT",
            "name": "TYPE_R_DEFAULT",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-RobustStats.html#constant_TYPE_R_DEFAULT"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\StatsComparator",
            "name": "StatsComparator",
            "summary": "StatsComparator\u0020\u002D\u0020Comparative\u0020analysis\u0020service.",
            "url": "classes/Cjuol-StatGuard-StatsComparator.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\StatsComparator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-StatsComparator.html#method___construct"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\StatsComparator\u003A\u003Aanalyze\u0028\u0029",
            "name": "analyze",
            "summary": "Compare\u0020metrics\u0020and\u0020return\u0020a\u0020data\u0020fidelity\u0020report.",
            "url": "classes/Cjuol-StatGuard-StatsComparator.html#method_analyze"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\StatsComparator\u003A\u003AgenerateVerdict\u0028\u0029",
            "name": "generateVerdict",
            "summary": "Generate\u0020a\u0020human\u002Dreadable\u0020conclusion\u0020based\u0020on\u0020the\u0020data.",
            "url": "classes/Cjuol-StatGuard-StatsComparator.html#method_generateVerdict"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\StatsComparator\u003A\u003A\u0024robust",
            "name": "robust",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-StatsComparator.html#property_robust"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\StatsComparator\u003A\u003A\u0024classic",
            "name": "classic",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-StatsComparator.html#property_classic"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Traits\\DataProcessorTrait",
            "name": "DataProcessorTrait",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Traits-DataProcessorTrait.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Traits\\DataProcessorTrait\u003A\u003AvalidateData\u0028\u0029",
            "name": "validateData",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Traits-DataProcessorTrait.html#method_validateData"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Traits\\DataProcessorTrait\u003A\u003AprepareData\u0028\u0029",
            "name": "prepareData",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Traits-DataProcessorTrait.html#method_prepareData"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Traits\\ExportableTrait",
            "name": "ExportableTrait",
            "summary": "",
            "url": "classes/Cjuol-StatGuard-Traits-ExportableTrait.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Traits\\ExportableTrait\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "Export\u0020the\u0020statistical\u0020summary\u0020to\u0020JSON.",
            "url": "classes/Cjuol-StatGuard-Traits-ExportableTrait.html#method_toJson"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Traits\\ExportableTrait\u003A\u003AtoCsv\u0028\u0029",
            "name": "toCsv",
            "summary": "Export\u0020the\u0020statistical\u0020summary\u0020to\u0020CSV.",
            "url": "classes/Cjuol-StatGuard-Traits-ExportableTrait.html#method_toCsv"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard",
            "name": "StatGuard",
            "summary": "",
            "url": "namespaces/cjuol-statguard.html"
        },                {
            "fqsen": "\\Cjuol",
            "name": "Cjuol",
            "summary": "",
            "url": "namespaces/cjuol.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Contracts",
            "name": "Contracts",
            "summary": "",
            "url": "namespaces/cjuol-statguard-contracts.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/cjuol-statguard-exceptions.html"
        },                {
            "fqsen": "\\Cjuol\\StatGuard\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/cjuol-statguard-traits.html"
        }            ]
);
